### ISSUE TITLE
[FEATURE] Rank creating menu for gangs

### ISSUE THREAD

**Issue by Teca1997** [Stuyk/altV-Open-Roleplay#101]
### Describe the Feature
Make a tab under the gangs' menu (U) where the owner can create a new rank and customize them to his liking.

### Describe how it should Work
When you create a new rank put tick boxes(or some other form of enabling and disabling options) to various options as Can invite other people/Can kick members, Can use gangs crafting point, Can manage the gang and etc.

**Comment by Stuyk** [comment]
Added into factions as of 3 or 4 days ago.
