### ISSUE TITLE
Mine door closed

### ISSUE THREAD

**Issue by Teca1997** [Stuyk/altV-Open-Roleplay#106]
### Describe the bug (What the bug is)
Mine in the center of the map has its doors closed.

### Reproducing the Bug (Steps)
Go to the mine in the center of the map.

### Expected Behavior (How this should be performing)
Doors should be open.

### Potential Solution Description (Optional)
n/a

**Comment by Stuyk** [comment]
Not a bug; just right-click the door it'll disappear.
