### ISSUE TITLE
Server simply quits when trying to use a repairkit

### ISSUE THREAD

**Issue by eappels** [Stuyk/altV-Open-Roleplay#108]
### Describe the bug (What the bug is)
The server simply quits without any error on server or client side after using a repairkit on a vehicle.
Apparently it does not always occur but then relog and try again. It should do it then.

### Reproducing the Bug (Steps)
Be admin (rank in DB)lvl 4
Crash your vehicle.
Add a repairkit to inventory using /additem repairkit
Use the repairkit on the vehicle
At this point I was disconnected on the client and server stopped.

### Expected Behavior (How this should be performing)
Server should keep running

### Potential Solution Description (Optional)
N/A

**Comment by Stuyk** [comment]
Cannot be reproduced.
