### ISSUE TITLE
/tempdoor creates doors with a slightly raised Z coordinate

### ISSUE THREAD

**Issue by openface** [Stuyk/altV-Open-Roleplay#111]
### Describe the bug (What the bug is)

Using /tempdoor to get coordinates for door placement seems to be setting up doors that have slightly raised Z positions. 
(The generated Z coordinate is higher than the visual temp door used during placement)

If you make the door visible, you'll see it's raised.

### Reproducing the Bug (Steps)
1. Use /tempdoor
2. Copy coordinates into new door JSON
3. Try to use it and notice the entity is raised.

### Expected Behavior (How this should be performing)

Door POS should not be raised.

**Comment by Stuyk** [comment]
Should be fixed now. Needs to be tested though. 5cfecfc6530c01f072bae031be9906a655cbbffe
