### ISSUE TITLE
Certain mechanics working badly?

### ISSUE THREAD

**Issue by Teca1997** [Stuyk/altV-Open-Roleplay#116]
### Describe the bug (What the bug is)
Seen in the video-

### Reproducing the Bug (Steps)
https://www.youtube.com/watch?v=-aBr9sdMYO8

### Expected Behavior (How this should be performing)
Not being able to do anything while performing those actions like refueling, repairing a car and so on.

### Potential Solution Description (Optional)
n/a

**Comment by Stuyk** [comment]
Resolved in eb91a5b3b7441607f06c9585a4ddee94ba204a4f
