### ISSUE TITLE
[Terms and Conditions]

### ISSUE THREAD

**Issue by IOxeOfficial** [Stuyk/altV-Open-Roleplay#122]
**Bug**
At the end of the install.js it asks me to accept the terms and conditions but there is no file as such in the repository.

**Fix**
Temporary fix create terms-and-conditions.json file

Could you explain to me why it doesn't come out or what I have to do to make it work

**Comment by Stuyk** [comment]
Not seeing this issue. Can't reproduce. No reproduction steps provided.
