### ISSUE TITLE
Inability to aim and shot after adding weapon

### ISSUE THREAD

**Issue by BERL1-Dev** [Stuyk/altV-Open-Roleplay#129]
### Describe the bug (What the bug is)
the bug is just that we can't aim and shoot with any type of weapon .... (and we can't punch other players, I don't know if it's done express but I want to report it too)

### Reproducing the Bug (Steps)
1. Open chat
2. wrinting "/addwep pistol"
3. Use the weapon from inventory
4. Weapon in arme, but impossible to use it.

### Expected Behavior (How this should be performing)
No idea.

### Potential Solution Description (Optional)
I dont know how i can give a solution.

**Comment by aktah** [comment]
Isn't it because it is in Safezone?

**Comment by Setraxis** [comment]
No, i can use weapons because this is a reason of wring implementation of it function..

on my test host somebody can use weapons because i reenabled the think how you can use weapons because he disabled any actions like slap peoples

**Comment by Stuyk** [comment]
Not an issue.
