### ISSUE TITLE
EquipItem (Tools)

### ISSUE THREAD

**Issue by aktah** [Stuyk/altV-Open-Roleplay#130]
### Describe the bug (What the bug is)
Example If you have axe level 0 and level 10. When equip axe level 0, you will receipt notify about restriction

### Reproducing the Bug (Steps)
1. Crafting Tools
2. Equip old tools

### Expected Behavior (How this should be performing)
`    
const inventoryIndex = player.inventory.findIndex(i => {
        if (i && i.hash === hash) return i;
});
`
I think issue is here from equipitem.js

**Comment by Stuyk** [comment]
Not an issue. Different tools have different levels of restrictions. ie. A woodcutting level of 10 is required for the level 10 version of an axe.

**Comment by aktah** [comment]
But they can't use axe level 0 if have axe level 10 (I mean, have both of these items.)

**Comment by aktah** [comment]
Okay It's come again, that random happen. 

Test: https://gfycat.com/idlecourageoushorsefly
- give hammer
- press 'i' -> Use
- Restriction skill alert

I check at database found this
`{"name":"ค้อนขึ้นสนิม","base":"hammer","key":"hammer","props":{"lvl":{"skill":"smithing","requirement":20,"bonus":6},...`
Why requirement upper to 20.

**Comment by Stuyk** [comment]
Hammer requires a smithing level. Verify with an increased smithing level for me.
